version: "3.8"

services:
  web:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  storybook:
    image: rayout-system_web
    ports:
      - 6006:6006
    volumes:
      - ./:/app
    command: npm run storybook
